FROM nginx:alpine

# RUN apk --no-cache update \
#   && apk --no-cache upgrade \
#   && apk --no-cache add \
#   && mkdir -p /var/www/app \
#   && chmod 755 -R /var/www/app

RUN apk --no-cache update \
  && apk --no-cache upgrade

# COPY docker/nginx-web/etc/nginx/nginx.conf /etc/nginx/nginx.conf
